services:
  kafka-1:
    image: apache/kafka:latest
    container_name: kafka-1
    ports:
      - 9092:9092
    environment:
      - CLUSTER_ID=4L6g3nShT-eMCtK--X86sw
      # Settings required for KRaft mode
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER
      # Configure listeners for both docker and host communication
      - KAFKA_LISTENERS=CONTROLLER://:9091,HOST://localhost:9092,DOCKER://:9093
      - KAFKA_ADVERTISED_LISTENERS=HOST://localhost:9092,DOCKER://:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
#      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_NUM_PARTITIONS=3
#      - KAFKA_LOG_DIRS=/tmp/kafka-logs
    volumes:
      - ./volumes/kafka-1/:/etc/kafka/secrets
      - ./volumes/kafka-1/:/mnt/shared/config
      - ./volumes/kafka-1/:/var/lib/kafka/data
      - ./volumes/kafka-1/:/tmp/kafka-logs
  kafka-2:
    image: apache/kafka:latest
    container_name: kafka-2
    ports:
      - 9093:9092
    environment:
      - CLUSTER_ID=4L6g3nShT-eMCtK--X86sw
      # Settings required for KRaft mode
      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER
      # Configure listeners for both docker and host communication
      - KAFKA_LISTENERS=CONTROLLER://:9091,HOST://localhost:9092,DOCKER://:9093
      - KAFKA_ADVERTISED_LISTENERS=HOST://localhost:9092,DOCKER://:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
#      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_NUM_PARTITIONS=3
#      - KAFKA_LOG_DIRS=/tmp/kafka-logs
    volumes:
      - ./volumes/kafka-2/:/etc/kafka/secrets
      - ./volumes/kafka-2/:/mnt/shared/config
      - ./volumes/kafka-2/:/var/lib/kafka/data
      - ./volumes/kafka-2/:/tmp/kafka-logs
  kafka-3:
    image: apache/kafka:latest
    container_name: kafka-3
    ports:
      - 9094:9092
    environment:
      - CLUSTER_ID=4L6g3nShT-eMCtK--X86sw
      # Settings required for KRaft mode
      - KAFKA_NODE_ID=3
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER
      # Configure listeners for both docker and host communication
      - KAFKA_LISTENERS=CONTROLLER://:9091,HOST://localhost:9092,DOCKER://:9093
      - KAFKA_ADVERTISED_LISTENERS=HOST://localhost:9092,DOCKER://:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
#      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_NUM_PARTITIONS=3
#      - KAFKA_LOG_DIRS=/tmp/kafka-logs
    volumes:
      - ./volumes/kafka-3/:/etc/kafka/secrets
      - ./volumes/kafka-3/:/mnt/shared/config
      - ./volumes/kafka-3/:/var/lib/kafka/data
      - ./volumes/kafka-3/:/tmp/kafka-logs
  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - 8070:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9093,kafka-2:9093,kafka-3:9093
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
