services:
  kafka-1:
    image: apache/kafka:latest
    ports:
      - 9092:9092
    environment:
#      - HOSTNAME=host.docker.internal
#      - KAFKA_KRAFT_CLUSTER_ID=4L6g3nShT-eMCtK--X86sw
      # Settings required for KRaft mode
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Configure listeners for both docker and host communication
      - KAFKA_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://${HOSTNAME:-localhost}:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_LOG_DIRS=/tmp/kafka-logs
    volumes:
      - ./volumes/kafka-1/secrets/:/etc/kafka/secrets
      - ./volumes/kafka-1/config/:/mnt/shared/config
      - ./volumes/kafka-1/data/:/var/lib/kafka/data
      - ./volumes/kafka-1/logs/:/tmp/kafka-logs
  kafka-2:
    image: apache/kafka:latest
    ports:
      - 9093:9093
    environment:
#      - HOSTNAME=host.docker.internal
#      - KAFKA_KRAFT_CLUSTER_ID=4L6g3nShT-eMCtK--X86sw
      # Settings required for KRaft mode
      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Configure listeners for both docker and host communication
      - KAFKA_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9090,EXTERNAL://${HOSTNAME:-localhost}:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_LOG_DIRS=/tmp/kafka-logs
    volumes:
      - ./volumes/kafka-2/secrets/:/etc/kafka/secrets
      - ./volumes/kafka-2/config/:/mnt/shared/config
      - ./volumes/kafka-2/data/:/var/lib/kafka/data
      - ./volumes/kafka-2/logs/:/tmp/kafka-logs
  kafka-3:
    image: apache/kafka:latest
    ports:
      - 9094:9094
    environment:
#      - HOSTNAME=host.docker.internal
#      - KAFKA_KRAFT_CLUSTER_ID=4L6g3nShT-eMCtK--X86sw
      # Settings required for KRaft mode
      - KAFKA_NODE_ID=3
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Configure listeners for both docker and host communication
      - KAFKA_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9090,EXTERNAL://${HOSTNAME:-localhost}:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_LOG_DIRS=/tmp/kafka-logs
    volumes:
      - ./volumes/kafka-3/secrets/:/etc/kafka/secrets
      - ./volumes/kafka-3/config/:/mnt/shared/config
      - ./volumes/kafka-3/data/:/var/lib/kafka/data
      - ./volumes/kafka-3/logs/:/tmp/kafka-logs
  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - 8070:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9090,kafka-2:9090,kafka-3:9090
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
  